### ISSUE TITLE
_tkinter.TclError: can't find package Thread / RuntimeError: Calling Tcl from different apartment on Windows 10.

### ISSUE THREAD

**Issue by Jakar510** [serwy/tkthread#2]
See original issue: https://github.com/serwy/tkthread/issues/1

Is there a way to get this working on Windows 10 or is it only linux?

**Comment by serwy** [comment]
What version of Python are you running?

**Comment by Armster15** [comment]
I have the same issue - though I'm using 3.6.8.

**Comment by Jakar510** [comment]
sorry for long delay. Python 3.7.3  32bit.

**Comment by Armster15** [comment]
I found a solution - the problem arises since the built in Tcl can't find the `Thread` package. I am linking the Tcl package `thread2.8.4` to this comment. Extract the zip file and drag and drop the folder `thread2.8.4` to C:\YourPythonInstallationDir\tcl\tcl8.6

Download package here: [thread2.8.4.zip](https://github.com/serwy/tkthread/files/4258625/thread2.8.4.zip)

This isn't the best solution in my opinion but is the only one as of now :\

**Comment by blanco-ether** [comment]
I think error I am seeing is same as reported here...

    Traceback (most recent call last):
     File "./progress.py", line 28, in <module>
     tkt = TkThread(root)  # make the thread-safe callable
       File "/home/pi/work/rpi_test/lib/python3.7/site-packages/tkthread/__init__.py", line 120, in 
    __init__
    self.root.eval('package require Thread')
    _tkinter.TclError: can't find package Thread

Python 3.7  Tkinter 8.6 Running on Raspbian Strech.

Do I need to install Tcl Thread library?  The lib armaan115 suggests has a .dll which seem to indicate windows only.  Is linux version available or can I build from source?

Thanks

**Comment by Armster15** [comment]
I'm pretty sure it should work regardless of the operating systems since it has the tcl files. I may be wrong though

**Comment by JasonGross** [comment]
@armaan115 
```
    tkt = TkThread(window)  # make the thread-safe callable
  File "D:\Program Files (x86)\Python38-32\lib\site-packages\tkthread\__init__.py", line 120, in __init__
    self.root.eval('package require Thread')
_tkinter.TclError: couldn't load library "D:/Program Files (x86)/Python38-32/tcl/tcl8.6/thread2.8.4/thread284t.dll": Bad exe format. Possibly a 32/64-bit mismatch.
```

**Comment by Armster15** [comment]
> @armaan115 
> ```
>     tkt = TkThread(window)  # make the thread-safe callable
>   File "D:\Program Files (x86)\Python38-32\lib\site-packages\tkthread\__init__.py", line 120, in __init__
>     self.root.eval('package require Thread')
> _tkinter.TclError: couldn't load library "D:/Program Files (x86)/Python38-32/tcl/tcl8.6/thread2.8.4/thread284t.dll": Bad exe format. Possibly a 32/64-bit mismatch.
> ```

Based on the name of the directory where python is installed, you are running a 32 bit version of python. The files I have attached are from a 64bit installation of python. I will send a 32 bit friendly version of the files also.

**Comment by Armster15** [comment]
@JasonGross Ok I got the 32 bit version of the library. It is a bit older though (2.7.0 instead of 2.8.4) but here it is:
[[32BIT] thread2.7.0.zip](https://github.com/serwy/tkthread/files/4834871/32BIT.thread2.7.0.zip)

**Comment by JasonGross** [comment]
Thanks!  I will try this the next time I use tcl (I gave up for now and decided to just write a console app this time)

**Comment by serwy** [comment]
The `tkinstall()` will allow multithreading support without needing the Tcl `Thread` package. It has been verified to work on Windows 10 using WinPython 3.9.4.
