### ISSUE TITLE
does this work with Tcl, if yes, can you provide an example

### ISSUE THREAD

**Issue by abunimeh** [serwy/tkthread#3]
```
from tkinter import Tcl

Tcl().eval("something")
```
errors out with `Calling Tcl from different apartment`

**Comment by serwy** [comment]
Calling `.eval` needs to be on the same thread as where Tcl was instantiated. Tkthread can't remove this requirement from the underlying Tcl/Tk library. Tkthread assumes that the Tk event loop will run from the main thread and be able to dispatch events from the main thread.

```
import tkthread; root = tkthread.tkinstall(ensure_root=True)
import tkinter as tk
import threading

thread_main_tcl = tk.Tcl()  # Tcl instance is bound to the main thread

def example():
    print(threading.current_thread())

    thread_local_tcl = tk.Tcl()  # Tcl instance is bound to the current thread

    r = thread_local_tcl.eval('set x 123')
    print('result', r)

    # tkthread.call will have thread_main_tcl.eval called on the main thread
    # and wait for the result.
    r = tkthread.call(thread_main_tcl.eval, 'set x 456')
    print('result', r)

    r = thread_main_tcl.eval('set x 789')   # will have error when not on main thread
    print('done')

example()  # run from main thread
threading.Thread(target=example, daemon=True).start()  # run from other thread

root.after(2000, lambda: root.quit())
root.mainloop()  # block until .quit is called in 2 seconds
```

**Comment by abunimeh** [comment]
Thanks for the example.
I got the example using threads as shown above to work i.e. the print statement shows
`<Thread(Thread-1, started daemon 123145449607168)>`

However, I have a test app where it uses asyncio. With that `tkthread.call` seems to freeze on `thread_main_tcl.eval`.
I am not sure if this is the actual cause or not but the print statement shows
`<WorkerThread(AnyIO worker thread, started daemon 123145507508224)>`

Does it matter if asyncio is used or not?

i dont have a simple test case to show yet. Do you think asyncio

**Comment by serwy** [comment]
`tkthread.call` is synchronous. It blocks until it's been executed and the result made available, which causes the freeze you are seeing. If the asyncio event loop is running on the main thread rather than the Tkinter main event loop, then the call will be blocked indefinitely. You'll need to have the asyncio event loop cooperate with the Tkinter event loop.

**Comment by abunimeh** [comment]
Thanks for the hint. Here is method to handle the tk event loop with asyncio. The program no longer freezes.

using `asyncio.ensure_future(tk_main(root))` where `tk_main` abuses `root.update()` seems to work.

```
import asyncio
import time
from concurrent.futures import ThreadPoolExecutor
import threading
import tkthread

root = tkthread.tkinstall(ensure_root=True)
import tkinter as tk


def example(x=5):
    print(threading.current_thread())

    # thread_local_tcl = tk.Tcl()  # Tcl instance is bound to the current thread

    # r = thread_local_tcl.eval("set x 123")
    # print("result", r)

    # tkthread.call will have thread_main_tcl.eval called on the main thread
    # and wait for the result.
    r = tkthread.call(ev, "set spawn_id %s" % spwn_id)
    r = tkthread.call(ev, "match_max -i %s 100000000" % spwn_id)
    r = tkthread.call(ev, 'set prompt "$ "')
    r = tkthread.call(ev, "expect $prompt")
    r = tkthread.call(ev, "set command date")
    r = tkthread.call(ev, r"send $command\r")
    r = tkthread.call(ev, r"expect $command\r")
    r = tkthread.call(ev, r'expect -re "(.*)\r"')
    r = tkthread.call(ev, r"send \r")

    # r = thread_main_tcl.eval("set x 789")  # will have error when not on main thread
    print("example, done.")
    print(f"sleeping {x}")
    time.sleep(x)


async def tk_main(root):
    while True:
        root.update()
        await asyncio.sleep(0.05)


async def main():
    # Run example in the ThreadPoolExecutor
    await loop.run_in_executor(p, example, 5)


thread_main_tcl = tk.Tcl()  # Tcl instance is bound to the main thread
# shotcut for eval
ev = thread_main_tcl.eval

ev("global auto_path; lappend auto_path {/opt/brew/Cellar/expect/5.45.4_1/lib}")
ev("package require Expect")
spwn_id = ev("spawn sh; set spawn_id")

print("start test program")
example()

tkmain = asyncio.ensure_future(tk_main(root))

loop = asyncio.get_event_loop()
p = ThreadPoolExecutor(2)  # Create a ThreadPoolExecutor with 2 Threads
loop.run_until_complete(main())

tkmain.cancel()
```

**Comment by serwy** [comment]
I'm glad to see that the system is working for you.

An implication of the `root.update()` followed by the 0.05 second sleep is that each of the `tkthread.call` function calls will have up to 0.05 second delay for each call. I haven't investigated how to integrate the asyncio and tkthread event loops efficiently yet.

**Comment by abunimeh** [comment]
ipython has some %magic implementation which integrates their loop with tk's loop. That might be a good implementation.
